# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ydHhOvaDc1dzm_64zcGwCMu7P31koDwY
"""

import streamlit as st
import numpy as np
from PIL import Image

st.title("🍎 Apple Disease Detection")

st.write("Upload an apple leaf image to predict the disease.")

uploaded_file = st.file_uploader("Upload Image", type=["jpg", "png", "jpeg"])

if uploaded_file is not None:
    # Show image
    image = Image.open(uploaded_file)
    st.image(image, caption="Uploaded Image", use_column_width=True)

    # Preprocess image (just for display purpose)
    img = image.resize((224, 224))
    img = np.array(img) / 255.0

    st.success("✅ Image uploaded successfully!")

    # Dummy prediction (since TensorFlow not supported)
    st.warning("⚠️ Model prediction disabled due to TensorFlow compatibility issue on Streamlit Cloud.")

    # Example output (optional)
    class_names = ["Apple Scab", "Black Rot", "Cedar Apple Rust", "Healthy"]
    st.info(f"Example Output: {class_names[0]}")
