# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ydHhOvaDc1dzm_64zcGwCMu7P31koDwY
"""

import streamlit as st
import numpy as np
from PIL import Image
from keras.models import load_model

model = load_model("apple_disease_model.keras")

class_names = ["Apple Scab", "Black Rot", "Cedar Apple Rust", "Healthy"]

st.title("🍎 Apple Disease Detection")

uploaded_file = st.file_uploader("Upload Apple Leaf Image", type=["jpg","png"])

if uploaded_file:
    image = Image.open(uploaded_file)
    st.image(image, caption="Uploaded Image")

    img = image.resize((224,224))
    img = np.array(img)/255.0
    img = img.reshape(1,224,224,3)

    prediction = model.predict(img)
    predicted_class = class_names[np.argmax(prediction)]

    st.success(f"Prediction: {predicted_class}")
